# Generated by Django 2.2 on 2020-12-18 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='boolean',
            new_name='complete',
        ),
    ]
